version: '3.8'
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/29

services:
    php-apache:
      container_name: web_name
      image: vcandela/php8-apache
      build:
          context: ./php
          dockerfile: Dockerfile
      volumes:
          - ./core:/var/www/html/
      ports:
          - 9090:80
      networks:
          frontend:
              ipv4_address: 172.20.0.3